services:
  s3gw:
    environment:
      GW_CRED_0_PERMISSIONS: ${GW_CRED_0_PERMISSIONS}
      GW_CRED_0_BUCKET_PERMISSIONS: ${GW_CRED_0_BUCKET_PERMISSIONS}
      GW_CRED_0_BUCKETS: ${GW_CRED_0_BUCKETS}
      ALLOW_BUCKET_CREATION: ${ALLOW_BUCKET_CREATION:-true}